spring:
  config:
    activate:
      on-profile: real
    profiles:
      group:
        local:
          - real-db
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  session:
    store-type: jdbc