spring:
  config:
    activate:
      on-profile: real
  session:
    store-type: jdbc
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mariadb://study-mybox.cu5pxrldea8y.ap-northeast-2.rds.amazonaws.com:3306/numble
    username: juu
    password: aa8270788*
    driver-class-name: org.mariadb.jdbc.Driver